name: Update BobGroupWindowsServer

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  PUBLISH_FOLDER: 'publish'
  PROJECT_FILE: 'PomogatorBot.Web\PomogatorBot.Web.csproj'
  WEBSITE_NAME: '!bob217pomogator'
  WEBSITE_PATH: 'E:\publish\bob217pomogator\production\web'

jobs:
  build-and-deploy:
    runs-on:
      labels: BobGroupWindowsServer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_FILE }}

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_FILE }} -c Debug -o ${{ env.PUBLISH_FOLDER }}

    - name: Stop IIS Website
      run: |
        Import-Module WebAdministration
        Stop-WebAppPool -Name "${{ env.WEBSITE_NAME }}"
      shell: pwsh

    - name: Copy new files
      run: Copy-Item -Path "${{ env.PUBLISH_FOLDER }}\*" -Destination "${{ env.WEBSITE_PATH }}" -Recurse -Force -Exclude "web.config", "appsettings.json"
      shell: pwsh

    - name: Start IIS Website
      run: |
        Import-Module WebAdministration
        Stop-WebAppPool -Name "${{ env.WEBSITE_NAME }}"
      shell: pwsh
