name: Update BobGroupWindowsServer

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  PUBLISH_FOLDER: 'publish'
  PROJECT_FILE: 'PomogatorBot.Web\PomogatorBot.Web.csproj'
  WEBSITE_NAME: '!bob217pomogator'
  WEBSITE_PATH: 'E:\publish\bob217pomogator\production\web'

jobs:
  build-and-deploy:
    if: |
      github.event_name == 'workflow_dispatch' || 
      !github.event.repository.fork
    runs-on:
      labels: BobGroupWindowsServer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: Restore dependencies
        run: dotnet restore --locked-mode ${{ env.PROJECT_FILE }}

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_FILE }} -c Debug -o ${{ env.PUBLISH_FOLDER }}

      - name: Stop IIS Website
        run: |
          Import-Module WebAdministration
          $appPool = Get-WebAppPoolState -Name "${{ env.WEBSITE_NAME }}"
          if ($appPool.Value -ne "Stopped") {
              Stop-WebAppPool -Name "${{ env.WEBSITE_NAME }}"
              Write-Host "AppPool stopped successfully"
          } else {
              Write-Host "AppPool already stopped, skipping..."
          }
        shell: pwsh

      - name: Copy new files
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: |
            Write-Host "Copying files from ${{ env.PUBLISH_FOLDER }} to ${{ env.WEBSITE_PATH }}"
            Copy-Item -Path "${{ env.PUBLISH_FOLDER }}\*" -Destination "${{ env.WEBSITE_PATH }}" -Recurse -Force -Exclude "web.config", "appsettings.json"
          shell: pwsh

      - name: Start IIS Website
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "${{ env.WEBSITE_NAME }}"
        shell: pwsh
